### ISSUE TITLE
ImageMagick leaves behind a WGroupCW

### ISSUE THREAD

**Issue by raboof** [raboof/notion#247]
When the `display` tool from ImageMagick shows a little 'navigation window', and we close it, a WGroupCW is left behind.

**Comment by wilhelmy** [comment]
I think I've seen this happen with other software as well.

**Comment by raboof** [comment]
Would be useful to leave a note here when we notice it for other software - in case of `display` I think maybe the little window should have a titlebar anyway so perhaps in that case we should fix it with kludges.

**Comment by lsh-0** [comment]
I'm getting these *a lot* since the new release. I've noticed them magically appearing while switching between full screen (but windowed) games and panes, so Steam and Fallout 4, and I've just this minute notice Thunderbird leave one behind after sending an email. I saw the title change from "Write: ..." to "WGroupCW".

**Comment by wilhelmy** [comment]
Seems mumble also leaves a WGroupCW

**Comment by lsh-0** [comment]
Bumping this as it's still happening dozens of times a day for me.

Is it a matter of being able to replicate the issue? Would it help if I supplied my config files?

**Comment by raboof** [comment]
No, I think it's more a matter of digging in the code and diagnosing why those windows are left behind.

**Comment by lsh-0** [comment]
Like I mentioned, I use Thunderbird and send a lot of emails which is why it happens to me so often. Let me know if I can help at all.

**Comment by raboof** [comment]
are you comfortable building from source? I'm curious if this problem also existed before 
#231, so for example on commit 9a1cc04

**Comment by lsh-0** [comment]
I can give it a crack but might need some hand holding. Can I build it inside a docker container so I don't muddy up my system?

**Comment by raboof** [comment]
I think so - there are some tools in `utils/docker` but I don't think we have any good documentation explaining them. That would be useful to add as well ;)
